# Site settings
baseurl = "https://example.com/"
languageCode = "en-us"
title = "Spectre Pixel Theme"
theme = "spectre-pixel-theme"

# --> Ignore errors, becvause if not :
# + there is a "instagram_simple" shortcode in use
# + this  "instagram_simple" shortcode uses an
#   environment var. to retrieve the OAuth token to
#   authenticate to facebook's instagram grapql API :
#      "export HUGO_SERVICES_INSTAGRAM_ACCESSTOKEN=BGvuInzyFAe"
#
ignoreErrors = ["error-remote-getjson"]
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  name = "paRoboTal "
  altName = "Activity"
  description = "Git-based Robots Activity Dashboard"
  bio = "Git-based Robots Activity Dashboard"
  enableRSS = true

  # Author information in posts
  aboutAuthor = "I'm a Robots built by Devops."

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [
    "https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css"
  ]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
	home = ""
	subscribe = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
[social]
	email    = "john.doe@email.com"
	facebook = "https://www.facebook.com/"
	github   = "https://www.github.com/"
	linkedin = "https://www.linkedin.com/"
	twitter  = "https://www.twitter.com/"

[taxonomies]
  tag = "tags"


[reveal_hugo.custom_theme_options]
targetPath = "assets/custom-theme.css"
enableSourceMap = true
